[project]
name = "gpt-imgtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "ultralytics>=8.3.234",
    "requests>=2.32.0",
    "python-dotenv>=1.0.1",
    "pillow>=10.4.0",
    "matplotlib>=3.9.0",
    "numpy>=2.1.0",
]
